apiVersion: apps/v1
kind: Deployment
metadata:
  name: harshitdemo01-deployment
spec:
  selector:
    matchLabels:
      app: harshitdemo01-pod
  template:
    metadata:
      labels:
        app: harshitdemo01-pod
    spec:
      containers:
      - name: harshitdemo01-container
        image: sidlabacr03.azurecr.io/harshitdemo01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000